go.property("camera_id", hash(""))

function init(self)
	print("Background 0 created!")
	self.parallax_speed = 5
	self.parallax_move = vmath.vector3(0, 0, 0)
end

function update(self, dt)
	local pos = go.get_position(self.camera_id)
	local dir = vmath.vector3(0, -1, 0)
	self.parallax_move = self.parallax_move + dir * dt * self.parallax_speed
	pos = pos + self.parallax_move
	go.set_position(pos)
end
