function init(self)
	-- Add initialization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
	print("Background 2 created!")
	self.speed = 40
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
	local pos = go.get_position()
	local dir = vmath.vector3(0, -1, 0)
	pos = pos + dir * self.speed * dt
	go.set_position(pos)
end